export ZSH="/Users/pw/.oh-my-zsh"

ZSH_THEME=""

plugins=(
  git
  docker 
  colored-man-pages 
  colorize
  copyfile 
  history
  zsh_reload
  extract
)

source $ZSH/oh-my-zsh.sh


export MANPATH="/usr/local/man:$MANPATH"

if [ -f '/Users/piotrwald/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/piotrwald/google-cloud-sdk/path.zsh.inc'; fi

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/dotfiles/antigen/antigen.zsh
source $HOME/.zshenv


# Bring in external plugins using Antigen
antigen bundle djui/alias-tips
antigen apply

# For a full list of active aliases, run `alias`.
alias drop_neo="rm -rf /usr/local/Cellar/neo4j/3.5.8/libexec/data/databases/graph.db"
alias pu="git push --force origin HEAD"
alias re="git reset HEAD~1"
alias wip="git add . && git commit -m 'WIP'"
alias subl="~/bin/subl"
alias p="cd ~/Projects"
alias dsa="docker stop $(docker ps -aq)"
alias dda="docker rm $(docker ps -aq)"
alias goo="cd $GOPATH"
alias rspec="bundle exec rspec"

export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
export PKG_CONFIG_PATH="/Users/piotrwald/Packages/seabolt-1.7.2-Darwin/usr/local/share/pkgconfig"
export LD_LIBRARY_PATH="/Users/piotrwald/Packages/seabolt-1.7.2-Darwin/usr/local/lib"
export GOPATH=$HOME/go
export PATH=$PATH:~/bin
export PATH="/usr/local/bin:$PATH"
export PATH=$PATH:~/.asdf/installs/elixir/1.9.0/.mix/escripts/
export PATH=$PATH:~/dotfiles/bin/
export ASDF_DIR=$(brew --prefix asdf)

autoload -U promptinit; promptinit
prompt pure

_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

load_cubiware_env_variables() {
  # source ~/Projects/dev.env
  if [ -f ~/workspace/cubi/main/dev.env ]; then
    set -a allexport
    . ~/workspace/cubi/main/dev.env
    set +a allexport
  fi
}

ensure_tmux_is_running
load_cubiware_env_variables

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

export LC_ALL=en_US.UTF-8

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pw/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/pw/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/pw/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/pw/google-cloud-sdk/completion.zsh.inc'; fi
