export ZSH="/Users/piotrwald/.oh-my-zsh"

ZSH_THEME=""

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  # docker 
  # zsh-autosuggestions 
  # aws 
  # colored-man-pages 
  # colorize
  # copydir 
  # copyfile 
  # gitignore
  # heroku
  # history
  # zsh_reload
  # npm
  # node
  # extract
  # osx
)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/piotrwald/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/piotrwald/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/piotrwald/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/piotrwald/google-cloud-sdk/completion.zsh.inc'; fi

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/antigen/antigen.zsh
source $HOME/.zshenv


# Bring in external plugins using Antigen
antigen bundle djui/alias-tips
antigen apply

# For a full list of active aliases, run `alias`.
alias drop_neo="rm -rf /usr/local/Cellar/neo4j/3.5.0/libexec/data/databases/graph.db"
alias lg="git log --abbrev-commit --pretty=oneline"
alias pu="git push --force origin HEAD"
alias re="git reset HEAD~1"
alias wip="git add . && git commit -m 'WIP'"
alias subl="~/bin/subl"
alias p="cd ~/Projects"

export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
export PKG_CONFIG_PATH="/Users/piotrwald/Packages/seabolt-1.7.2-Darwin/usr/local/share/pkgconfig"
export LD_LIBRARY_PATH="/Users/piotrwald/Packages/seabolt-1.7.2-Darwin/usr/local/lib"
export GOPATH=$HOME/go
export PATH=$PATH:~/bin
export PATH="/usr/local/bin:$PATH"

autoload -U promptinit; promptinit
prompt pure

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
